image: "node:latest"
stages:
  - test
  - build
  - deploy
  # - cleanup

variables:
  AWS_DEFAULT_REGION: us-east-1
  BUCKET_NAME: jaam.app

cache:
  paths:
    - node_modules

test_frontend:
  stage: test
  script:
    - yarn install --pure-lockfile
    - yarn check-ts
    - yarn test
  only:
    - /^issue-.*$/
    - dev
    - master

build_frontend:
  stage: build
  script:
    - yarn install --pure-lockfile
    - yarn build
  only:
    - /^issue-.*$/
    - /^qa-build.*$/
    - /^prod-build.*$/
    - master
  artifacts:
    paths:
      - dist/

deploys3:
  image: "python:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - build_frontend      # We want to specify dependencies in an explicit way, to avoid confusion if there are different build jobs
  only:
    - /^never/
  before_script:
    - pip install awscli # Install the SDK
  script:
    - aws s3 cp dist s3://${BUCKET_NAME} --recursive --exclude index.html # Replace example-bucket with your bucket
    - aws s3 cp dist/index.html s3://$S3_BUCKET_NAME/index.html --cache-control max-age=0,no-cache,no-store,must-revalidate
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_COMMIT_REF_SLUG}  # This is the url of the bucket we saved before
    # on_stop: clean_s3

# clean_s3:
#   image: "python:latest"
#   stage: cleanup
#   before_script:
#     - pip install awscli
#   script:
#     - aws s3 rm s3://${BUCKET_NAME}/${CI_COMMIT_REF_SLUG} --recursive # Replace example-bucket with your bucket
#   environment:
#     name: ${CI_COMMIT_REF_SLUG}
#     action: stop
#   when: manual

qa_deploy:
  extends: deploys3
  only:
    - /^qa-build.*$/
  variables:
    NODE_ENV: development
    BUCKET_NAME: dev.jaam.app

prod_deploy:
  extends: deploys3
  only:
    - /^prod-build.*$/
    - master
  variables:
    NODE_ENV: production
    BUCKET_NAME: jaam.app
  when: manual

# build_frontend:  # A job to build the static website - replace it with your build methods
#   stage: build
#   script:
#     - yarn install --pure-lockfile
#     - yarn build
#   artifacts:
#     paths:
#       - build/  # This is what we want to publish
