version: '3'
services:
  ws:
    build: .
    command: yarn nodemon server/index.js
    ports:
      - "1337:1337"
    volumes:
      - .:/app

  parcel:
    build: .
    command: yarn parcel
    ports:
      - "1234:1234"
    volumes:
      - .:/app
